%% Organize a friggin file list into numerical order 



%% Use this section if you want to also rearrange an array along with fList
%point this variable to a struct generated by saying fList = dir('*.cxd');
fList = fList;
L = length(fList);

%point this variable to data to be rearranged
%should have same length as fList
data = results2;

dim = size(data);
if (dim(1)~=L)
   'Uh oh, mismatch data and file list'
end

%initialize new fList and data
fListSorted = fList;
dataSorted = data;

num=0;
for i=1:L
    j=0; %we want j to become 1 when we find a match 
    index = 1;
    while j==0
        % look for num in file list
        fname = fList(index).name;
        fnp = fname(end-6:end-4); %important part
        
        %drop charaters that might not be numbers
        if isnan(str2double(fnp))
            fnp = fnp(2:end);
            if isnan(fnp)
                fnp = fnp(end);
            end
        end
        
        %store the integer value of this file name
        I = str2double(fnp);
               
        %compare it to num
        if I==num
            fListSorted(i).name = fname;
            dataSorted(i,:) = data(index,:);
            num = num+1;
            j=1;
        else
            if index == L
                num = num+1;
                index = 1;
            else
                index = index+1;
            end
        end 
    end
    
    
end

%% Use this section if you just want to rearrange a file list
%point this variable to a struct generated by saying fList = dir('*.cxd');
fList = fList;
L = length(fList);

%initialize new fList and data
fListSorted = fList;

num=0;
for i=1:L
    j=0; %we want j to become 1 when we find a match 
    index = 1;
    while j==0
        % look for num in file list
        fname = fList(index).name;
        fnp = fname(end-6:end-4); %important part
        
        %drop charaters that might not be numbers
        if isnan(str2double(fnp))
            fnp = fnp(2:end);
            if isnan(fnp)
                fnp = fnp(end);
            end
        end
        
        %store the integer value of this file name
        I = str2double(fnp);
               
        %compare it to num
        if I==num
            fListSorted(i).name = fname;
            num = num+1;
            j=1;
        else
            if index == L
                num = num+1;
                index = 1;
            else
                index = index+1;
            end
        end 
    end
    
    
end


